name: app
description: Diaconn My App

publish_to: 'none'

version: 6.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: 0.1.3
  grouped_list: 3.3.0
  flutter_ble_lib: 2.2.6
  rxdart: 0.24.1
  permission_handler: 5.0.1+1
  provider: 4.3.2+1
  fluttertoast: 4.0.1
  intl: 0.16.1
  shared_preferences: 0.5.8
  http: 0.12.2
  fimber: 0.4.4
  fl_chart: 0.11.0
  flutter_staggered_grid_view: 0.3.2
  google_sign_in: 4.5.1
  sign_in_with_apple: 2.5.2
  flutter_svg: 0.18.0
  get_version: 0.2.2
  focus_detector: 1.0.3
  uuid: 2.2.0
  mask_text_input_formatter: 1.0.7
  url_launcher: 5.5.0
  flutter_spinkit: 4.1.2+1
  screen: 0.0.5
  firebase_core: 0.5.0
  firebase_auth: 0.18.0+1
  firebase_crashlytics: 0.1.4+1
  firebase_analytics: 6.0.0
  firebase_messaging: 7.0.0
  flutter_barcode_scanner: 1.0.1
  nfc_manager: 1.3.2+4
  json_table: 1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/common/
